[project]
channels = ["nvidia/label/cuda-11.8.0", "pytorch", "conda-forge"]
name = "flod"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build-viewer = { cmd="docker build -t viewer .", cwd="SIBR_viewers"}

[dependencies]
cuda = "*"
plyfile = "*"
python = "3.10.*"
pip = "22.3.1.*"
pytorch = "1.12.1.*"
torchaudio = "0.12.1.*"
torchvision = "0.13.1.*"
tqdm = "*"
mkl = "2024.0"
gcc = "11.*"
gxx = "11.*"
numpy = "1.26.4"
tensorboard = ">=2.18.0,<3"

[pypi-options]
no-build-isolation = ["diff-gaussian-rasterization", "simple-knn"]
[pypi-dependencies]
open3d = "*"
opencv-python = "*"
diff-gaussian-rasterization = { path = "submodules/diff-gaussian-rasterization" }
simple-knn = { path = "submodules/simple-knn" }

[target.unix.activation.env]
DATASET_DIR = "/home/edvardsz/Desktop/360_v2/"
CUDA_HOME = "$CONDA_PREFIX"
